### ISSUE TITLE
update backend

### ISSUE THREAD

**Issue by thainguyencoffee** [thainguyencoffee/bookstore-full-stack#117]
from #116 

- [x] refactor User&Address (Information) #118 
- [x] Adding models (Author, Quotation, EBook, PrintBook) #118 
- [x] Book remove property (purchaseAt) reason: purchaseAt is a property of the Purchase Order, #118 
- [x] rename audit data from _at to _date #118 
- [x] Migration Book to Book + (EBook and PrintBook) #118 
- [x] remove endpoint /api/best-sellers reason: invalid #118 
- [x] update best-sellers #118 
- [x] use data.sql with @ParameterizedTest + @MethodSource instead of @test for data test available and more safety. #118 
- [x] Adding some valuetype for Book module and for global #118 
- [x] update bean validation and tests bean validation #118 
- [x] book service probably not clean (enhancement) #118 
- [x] LineItemRequest adding bookType prop to recognize type of book #118 
- [x] change /api/foo/** to /foo/** #118 

- [ ] thay đổi ebook với ebook file để quản lý dễ hơn (1 ebook thì có nhiều ebook file, xóa mối quan hệ 1 book nhiều ebook và 1 book nhiều print book -> chuyển sang 1 book chỉ chứa 1 ebook và 1 printbook #119 )
- [ ] email service give some issue hasn't completed yet

**Comment by thainguyencoffee** [comment]
- [ ] email service give some issue hasn't completed yet
